### ISSUE TITLE
JupyterHub authenticator that reads username / passwords from a CSV file

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/outreachy#1]
JupyterHub authenticators can use any data source to validate the username / passwords users give them. In some cases, administrators want to make a [CSV](https://en.wikipedia.org/wiki/Comma-separated_values) file containing usernames and password as columns, and let users log in to JupyterHub with that.

For this task, write and publish (as a GitHub repository) a JupyterHub authenticator that:

1. Requires a configuration value that points to an existing CSV file with two columns: username & password
2. Users with an entry in the CSV can log in with their password
3. If a username doesn't exist in the CSV, they can not log in.

Helpful links:

1. Tornado tutorial: http://www.tornadoweb.org/en/stable/
2. https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html#how-to-write-a-custom-authenticator has information on writing a custom authenticator
3. https://github.com/yuvipanda/jupyterhub-simplespawner is a useful spawner class to test authenticator implementations
4. https://github.com/yuvipanda/jupyterhub-dummy-authenticator is an example of a very simple authenticator you can look for inspiration

Getting Help:

Comment on this issue, or ping us [on Gitter](https://gitter.im/jupyterhub/jupyterhub) for help!

**Comment by yuvipanda** [comment]
@Anisha1234 awesome :) You're already on gitter, so feel free to continue asking us questions there. Welcome to the community :)

**Comment by minrk** [comment]
This task is now available to be assigned again. Thanks for working on it, @Anisha1234!

**Comment by GeorgianaElena** [comment]
Hi! I would like to give it a try :)

**Comment by GeorgianaElena** [comment]
Actually, I've just realized this issue is related to the nativeauth project. @minrk, do you think it's a good idea for me to work on this issue, or should I pick something more related to traefik?

**Comment by Naba7** [comment]
hi .I want to work on this issue.I am trying to explore in here

**Comment by JoyLubega** [comment]
Thanks @minrk
