### ISSUE TITLE
Move simplespawner into JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/outreachy#11]
See https://github.com/jupyterhub/jupyterhub/issues/2168

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here or [on gitter](https://gitter.im/jupyterhub/jupyterhub) if you have questions :)

**Comment by kshitija08** [comment]
@minrk, @yuvipanda  I want to work on this issue. Kindly, guide me.

**Comment by minrk** [comment]
@kshitija08 great! There is a Spawner class defined [here](https://github.com/jupyterhub/simplespawner/blob/master/simplespawner/simplespawner.py). We've learned that this is sufficiently useful that we should include it in the base JupyterHub repo, by copying it over to [here](https://github.com/jupyterhub/jupyterhub), likely creating a new directory `jupyterhub/spawners`.

**Comment by kshitija08** [comment]
@minrk @yuvipanda I have made a pull request for this issue. Kindly, let me know if it has some errors as this is my first ever pull request.

**Comment by minrk** [comment]
This task is complete. Thank you!
