### ISSUE TITLE
Move DummyAuthenticator into JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/outreachy#12]
See https://github.com/jupyterhub/jupyterhub/issues/2169

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here or [on gitter](https://gitter.im/jupyterhub/jupyterhub) if you have questions :)

**Comment by kyla-harper** [comment]
I'm interested in working on this. May I be assigned to this task?

**Comment by kyla-harper** [comment]
With the last two PR's merged, there are now tests, docs, and code for DummyAuthenticator in the system. Are we good to close this?

**Comment by minrk** [comment]
@kyla-harper yes, I think so. Thank you!
