### ISSUE TITLE
pytest plugin: pytest-jup_hub

### ISSUE THREAD

**Issue by Sheila-nk** [jupyterhub/outreachy#127]
### Please share the URL of pytest plugin you have created?

https://github.com/Sheila-nk/pytest-jup_hub/tree/main

### Please share the URL to your fork of `FirstUseAuthenticator` where you have integrated the plugin

https://github.com/Sheila-nk/firstuseauthenticator/tree/pytest-plugin

### Whether or not you managed to run the `FirstUseAuthenticator` tests succesfully

Yes, the tests run

#40

**Comment by sgibson91** [comment]
Thank you for your contribution! Since the contribution period is now over, we will close this issue.
