### ISSUE TITLE
Add 'running_servers' prometheus metric to JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/outreachy#13]
See https://github.com/jupyterhub/jupyterhub/issues/2170

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here or [on gitter](https://gitter.im/jupyterhub/jupyterhub) if you have questions :)

**Comment by GeorgianaElena** [comment]
Hi! I've submitted a pull request addressing this issue as part of Outreachy. I'm not sure this is the intended behavior of the metric, any feedback would be highly appreciated :).

https://github.com/jupyterhub/jupyterhub/pull/2176

**Comment by minrk** [comment]
Thanks for implementing this one!
