### ISSUE TITLE
Preparing to onboard the interns

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/outreachy#138]
Some questions around what we may need to setup before the interns begin

- should we meet with them for greetings before their official start date?
- what do we need to have ready for them before they start:
	- a plan for how to get and provide feedback
	- a repository ready for them to start working in
	- a set of initial issues or a plan on how to tackle the project
	- what documentation should they read before starting? is there any?
- how to welcome them in the community: inviting them to the monthly meetings
- maybe we can setup an initial "demo" meeting with Min (or others on the team) to get a high level overview of the current JupyterHub testing infra (same for the other projects)

**Comment by sgibson91** [comment]
I was going to send out an email to each intern that covered some of these topics:

- Arrange a regular meeting time with your mentor
- Here is a template document to keep notes from your meetings in
- Reach out to Community Coordinator (me) if there are any issues, or one of the other mentors if issue involves the Comm Coord

**Comment by GeorgianaElena** [comment]
Another idea:
Write a celebratory blog post in https://blog.jupyter.org to announce the interns and projects

**Comment by sgibson91** [comment]
> * a repository ready for them to start working in
> * a set of initial issues or a plan on how to tackle the project
> * what documentation should they read before starting? is there any?

I wonder if these points are fine to work through in the first week of the internship? For example depending on the skill level of the intern, including them in point 2 would be a great opportunity for them to take ownership of the work, and gain experience in the planning of projects, as opposed to just execution?

**Comment by minrk** [comment]
Yeah, I think that's a good idea. I'd be happy to do a demo meeting during the first week as well.

**Comment by sgibson91** [comment]
Ok, I have a to-do list for next week:

- [ ] Create some meeting notes templates to share
- [ ] Send out intro email for each intern/mentor set
  - [ ] Include when2meet for demo session in the first week
  - Include above meeting notes template
- [ ] Begin welcome blog post and ask interns for a few lines about them
- [ ] Setup first cohort call for interns

**Comment by sgibson91** [comment]
- Meeting notes template #144 (I quick merged this to avoid conflicts and I don't think it's too controversial)
- Intro email template #145

**Comment by sgibson91** [comment]
I think the interns are onboarded so closing this
