### ISSUE TITLE
Add server_stop_duration_seconds prometheus metric

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/outreachy#14]
See https://github.com/jupyterhub/jupyterhub/issues/2171

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here or [on gitter](https://gitter.im/jupyterhub/jupyterhub) if you have questions :)

**Comment by minrk** [comment]
This task has been completed. Thanks @tuhina2020!

**Comment by minrk** [comment]
@tuhina2020 could you make sure to record your contributions on the [outreachy page](https://www.outreachy.org/apply/project-selection/)?
