### ISSUE TITLE
Add server_poll_duration_seconds prometheus metric 

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/outreachy#16]
See https://github.com/jupyterhub/jupyterhub/issues/2185

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here or [on gitter](https://gitter.im/jupyterhub/jupyterhub) if you have questions :)

**Comment by GeorgianaElena** [comment]
Hi @yuvipanda! I'm blocked waiting for review on another issue. I will take a look at this one in the meantime

**Comment by minrk** [comment]
Great! I see you've already done a PR adding one of these metrics, so I think you are set. Feel free to ask questions if you have them, though.

**Comment by minrk** [comment]
This has been merged. Thanks, @GeorgianaElena!

**Comment by minrk** [comment]
@GeorgianaElena could you make sure that you have recorded your contributions on the [outreachy page](https://www.outreachy.org/apply/project-selection/)?
