### ISSUE TITLE
Apply for financial support for attending JupyterCon 2023

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/outreachy#163]
This issue is intending to track the process for applying for financial support to attend JupyterCon 2023 as Outreachy interns working with JupyterHub.

The scholarship and financial aid program for JupyterCon is outlined here: https://www.jupytercon.com/scholarship-and-finaid The deadline for submitting applications is **March 3rd 2023**.

I am recommending we follow the below guidelines:

- Confirmation of acceptance of abstract will be announced on **February 17th 2023** (or somewhere around then. This is from memory as I can't find anywhere that states this date any more.) We wait to see whose abstracts have been accepted or not.
- If your abstract has been accepted, **talk with your mentor(s) before confirming your talk**. We don't want to set you up to fail, so they may have ideas on how your talk should be changed based on how your project has progressed.
- If you're to go ahead with your talk, begin the process of applying for financial aid. Somewhere in your application you **must**:
  - **State that you are an Outreachy intern working with JupyterHub.** Members of the JupyterCon organising committee know that you are applying and are on the lookout for your applications.
  - **State that you require a formal letter of invitation for a VISA.** (If this does not come with the abstract acceptance notice.) I will probably also coordinate with the committee to ensure this is treated as high priority.

cc/ @alwasega @bl-aire @Sheila-nk

**Comment by alwasega** [comment]
Thanks a lot @sgibson91. Let the wait begin :)

**Comment by bl-aire** [comment]
🤞🤞🙂

**Comment by sgibson91** [comment]
Please begin working with your mentors to submit the financial support application if you intend to attend JupyterCon!

**Comment by sgibson91** [comment]
I have just emailed the JupyterCon committee asking about invitation letters for your visa applications

**Comment by Sheila-nk** [comment]
Thank you @sgibson91 that would be really helpful.
I was wondering what to state as the purpose of travel because different reasons have different requirements. For a business purpose to attend an event requires an employment letter which we won't have. Should I just state that it is for tourism?

**Comment by sgibson91** [comment]
> For a business purpose to attend an event requires an employment letter which we won't have. Should I just state that it is for tourism?

@damianavila Would you mind sharing your thoughts/experiences here?

(Damián is a colleague of mine who lives in Argentina and has much more experience of visa applications for conferences than I do)

**Comment by damianavila** [comment]
If you are going to an event, you are not actually doing tourism.
You always need to go with the truth to prevent any potential issues.
I do not have the details about the French visa process, but usually and generally speaking, a letter of invitation from the conference organization is enough to request a sort of business-like visa to enter the country.

**Comment by Sheila-nk** [comment]
Okay, thank you @sgibson91 and @damianavila

**Comment by GeorgianaElena** [comment]
@damianavila, so you're saying that the employment letter they require should be replaceable by the invitation letter from the conference, right?

Also, from experience, having a business visa has any implications for the amount of time one can spend in that foreign country? I am asking this because I know Sheila also wants to do some other traveling too. So a tourist + business might be desirable, but I don't how that would work.

**Comment by alwasega** [comment]
@Sheila-nk, I believe we would have to apply for a [short-stay] (https://france-visas.gouv.fr/en/web/france-visas/short-stay-visa) visa. A friend of mine who recently went to France gives the following as the required docs: 
- An application (to be completed and downloaded from https://france-visas.gouv.fr/en/web/ke)
- Original passport + Copy + previous schengen visas
- Flight booking 
- Travel health insurance
- Proof of accomodation
- Invitation letter
- Letter from employer
- Payslips/ bank statements for the last 3 months
- 2 passport photos
- Visa fees in cash (at the time he was making his application, this was KES 9,567)

** For flights and hotels, he says he made unpaid bookings. 
** For any questions, you can email visas.nairobi-amba@diplomatie.gouv.fr
** As he is a student, he used a letter from his university in place of the `Letter from employer.` This is where we can run into trouble :(

**Comment by sgibson91** [comment]
Regarding letter from employer, I have asked in Outreachy Zulip if this is something the Software Freedom Conservancy can offer (as you are technically self-employed contractors for that org)

**Comment by Sheila-nk** [comment]
> Also, from experience, having a business visa has any implications for the amount of time one can spend in that foreign country?

Yes, I am quite curious about this because I also want to visit some Schengen member states after the conference.

**Comment by Sheila-nk** [comment]
@alwasega that is really helpful information, thank you! The information on the website is pretty limited.

**Comment by sgibson91** [comment]
@Sheila-nk On [this page](https://france-visas.gouv.fr/en/web/france-visas/short-stay-visa) there is an expandable question "What is the maximum authorised duration for your stay in the Schengen Area?". They have a link to a [duration calculator](https://ec.europa.eu/assets/home/visa-calculator/calculator.htm?lang=en) for non-European nationals. But I think the upper limit is 90 days for your whole trip within the Schengen zone.

**Comment by sgibson91** [comment]
@alwasega @bl-aire @Sheila-nk Please see the email from Gayle Ollington requesting your passport number and country of origin for invitation letters! (Make sure not to reply all so everyone on the thread doesn't get your details :) )

**Comment by Sheila-nk** [comment]
Okay @sgibson91 thank you!

**Comment by bl-aire** [comment]
> @alwasega @bl-aire @Sheila-nk Please see the email from Gayle Ollington requesting your passport number and country of origin for invitation letters! (Make sure not to reply all so everyone on the thread doesn't get your details :) )

Thanks @sgibson91

**Comment by alwasega** [comment]
Thanks a lot @sgibson91!

**Comment by Sheila-nk** [comment]
Question: 
When applying for financial support there is this question:
**Due to limited funding we will be asking all candidates who are under consideration for funding to submit an expected expenses budget prior to confirmation of the support.**
So the expected expenses include the **return ticket**, **accommodation** and **event registration**. 
My question is about accommodation. How many days would we require accommodation sponsorship? So I can provide an estimate of how much that would be.

**Comment by sgibson91** [comment]
JupyterCon is happening for 3 days 10th-12th May. Given that you are travelling internationally, it is perfectly acceptable to have accommodation from the day before until the day after the conference, so 9th-13th, which is 4 nights.

**Comment by sgibson91** [comment]
🔥REMINDER🔥The deadline is tomorrow, so if you haven't yet submitted your application, please do so at your earliest convenience!

**Comment by alwasega** [comment]
Thank you @sgibson91. I submitted my application on 2nd March.

**Comment by Sheila-nk** [comment]
Yes! I submitted mine on Feb 27th.

**Comment by bl-aire** [comment]
I submitted mine too.

**Comment by sgibson91** [comment]
Good luck everyone!
