### ISSUE TITLE
Add optional authentication to /metrics endpoint in JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/outreachy#21]
See https://github.com/jupyterhub/jupyterhub/issues/2105

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here or [on gitter](https://gitter.im/jupyterhub/jupyterhub) if you have questions :)

**Comment by angelikamukhina** [comment]
Hello! I'd like to work on this issue:)

**Comment by minrk** [comment]
@angelikamukhina hi! This task is already being worked on by @tuhina2020. Please find another task.

**Comment by sgibson91** [comment]
I am closing this issue as it pertains to a previous round out Outreachy.
