### ISSUE TITLE
Benchmark JupyterHub proxy

### ISSUE THREAD

**Issue by minrk** [jupyterhub/outreachy#22]
We have the workings of a proxy benchmark suite in https://github.com/minrk/chpbench . This will be really useful as we start to develop the traefik proxy implementation.

This repo should be reorganized to use [airspeed velocity](https://asv.readthedocs.io/en/stable/) to run benchmarks, instead of a standalone script.

The first task should be to restructure the current code and two existing benchmarks (single_run_ws and single_run_http) into asv benchmark functions, and run them on travis.

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here or [on gitter](https://gitter.im/jupyterhub/jupyterhub) if you have questions :)

**Comment by kshitija08** [comment]
HEY @minrk , I would like to contribute to this issue. Can I get started ?

**Comment by minrk** [comment]
Yes, please go ahead!

**Comment by kshitija08** [comment]
@minrk Are the functions single_run_ws and single_run_http and not run_single_ws and run_single_http [def single_run_http(url, delay, size, msgs):](here). ?

**Comment by minrk** [comment]
Yes, in my description I used the wrong names. Updated just now.

**Comment by kshitija08** [comment]
@minrk Hey, I have made a PR regrading the same . Kindly, check .
https://github.com/minrk/chpbench/pull/2

**Comment by sgibson91** [comment]
Thanks for your contributions! I am closing this issue now as it pertains to a previous round out Outreachy.
