### ISSUE TITLE
Make JupyterHub proxy tests portable

### ISSUE THREAD

**Issue by minrk** [jupyterhub/outreachy#23]
JupyterHub [has tests](https://github.com/jupyterhub/jupyterhub/blob/0.9.4/jupyterhub/tests/test_proxy.py) for verifying the proxy.

It would be useful to refactor these tests (not including `test_external_proxy`) to take a Proxy instance instead of the `app` fixture. This will make it easier to re-use the same tests with different proxy implementations. It will require writing a [pytest fixture](https://docs.pytest.org/en/latest/fixture.html) to return the Proxy object.

To do this, the tests should use a fixture that returns a running Proxy, instead of talking to the application object.

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here or [on gitter](https://gitter.im/jupyterhub/jupyterhub) if you have questions :)

**Comment by willingc** [comment]
Welcome @Olena23. 

From gitter: 
> do I need to add a file with tests to the repo I forked or do I need to fork https://github.com/jupyterhub/jupyterhub and refactor the file with tests there?

The second one you mention. You will need to create a fork of jupyterhub/jupyterhub and refactor the tests in that repo. Hope this helps. Let us know if you need assistance with setting up the development environment.

**Comment by minrk** [comment]
Yes, it will specifically be the tests in `jupyterhub/tests/test_proxy.py` *excluding* `test_external_proxy`.

**Comment by minrk** [comment]
@Olena23 are you still working on this? If not, I'd like to make this task available to other applicants.

**Comment by Olena23** [comment]
Good day,

Yes, I am working on a task.
I started by reading the unit testing textbook and setting up and setting up the working environment.
At the moment I can run jupyterhub and use notebooks, and also I can run tests from the console, and they work (not counting 49 warnings).

![screenshot_20181024_012046](https://user-images.githubusercontent.com/28828146/47399043-1d53bb80-d737-11e8-8674-cf002d40380e.png)

Now I'm trying to figure out exactly how I need to rewrite the test code.

Do I understand correctly that the app is this object?

![screenshot_20181024_024331](https://user-images.githubusercontent.com/28828146/47399052-23e23300-d737-11e8-84cb-180f02eb6094.png)

And do I understand correctly that I need to write a other fixture for using for test_proxy.py methods, which will instantiate the object Proxy subclass for  (for example ConfigurableHTTPProxy)?

**Comment by minrk** [comment]
> Do I understand correctly that the app is this object?

yes, exactly

> do I understand correctly that I need to write a other fixture for using for test_proxy.py methods, which will instantiate the object Proxy subclass (for example ConfigurableHTTPProxy)?

Yes, that's exactly right. We want to, given a Proxy class, be able to run some tests with the proxy. A fixture that returns an instantiated and running Proxy would be a good start for that.

**Comment by sgibson91** [comment]
Thank you for your contributions! I am closing this issue now as it pertains to a previous round of Outreachy.
