### ISSUE TITLE
Document using the notebook's internal culling

### ISSUE THREAD

**Issue by minrk** [jupyterhub/outreachy#24]
See https://github.com/jupyterhub/jupyterhub/issues/2032

The notebook has its own culling mechanism, so it may be useful to use that for shutting down idle servers instead of the proxy-based activity tracking.

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here or [on gitter](https://gitter.im/jupyterhub/jupyterhub) if you have questions :)

**Comment by tuhina2020** [comment]
hello :) . can I start working on this bug ?

**Comment by minrk** [comment]
Yes, please go ahead @tuhina2020!

**Comment by minrk** [comment]
@tuhina2020 are you still working on this? If not, I'd like to mark this as available to other applicants.

**Comment by anyushevai** [comment]
Hi! I'd like giving it a try if this issue is available.

**Comment by consideRatio** [comment]
With https://github.com/jupyterhub/jupyterhub/issues/2032 closed, I figure  we can close this as well as resolved.
