### ISSUE TITLE
Implement idle-culling using notebook activity data

### ISSUE THREAD

**Issue by minrk** [jupyterhub/outreachy#25]
Right now, idle-culling relies on consuming data from the activity-tracking proxy. The notebook now tracks activity internally, so we could be talking to each notebook individually to make more informed decisions.

- the [cull-idle script](https://github.com/jupyterhub/jupyterhub/blob/master/examples/cull-idle/cull_idle_servers.py) could be updated to get last_activity data from the notebook api instead
- the notebook has a [status api](http://petstore.swagger.io/#/status/get_api_status) for reporting its current status

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here or [on gitter](https://gitter.im/jupyterhub/jupyterhub) if you have questions :)

**Comment by kshitija08** [comment]
@minrk Hey, I want to contribute to the above issue.

**Comment by minrk** [comment]
Since you've claimed #22, we will leave this available to others. Let's try to keep only one task claimed at a time so that other applicants can work on things as well.

**Comment by angelikamukhina** [comment]
Then may I work on this issue?

**Comment by minrk** [comment]
@angelikamukhina absolutely! Consider it assigned.

**Comment by sgibson91** [comment]
Thanks for your contributions! I am closing this issue now as it pertains to a previous round out Outreachy.
