### ISSUE TITLE
Document removing config values in the-littlest-jupyterhub

### ISSUE THREAD

**Issue by minrk** [jupyterhub/outreachy#30]
See https://github.com/jupyterhub/the-littlest-jupyterhub/issues/203

Add to the documentation of the littlest jupyterhub how to clear/remove config values.

**Comment by gillybops** [comment]
@minrk I will give this a try

**Comment by sgibson91** [comment]
Thanks for your contributions! I am closing this issue now as it pertains to a previous round of Outreachy.
