### ISSUE TITLE
Improve the test coverage of JupyterHub projects

### ISSUE THREAD

**Issue by GeorgianaElena** [jupyterhub/outreachy#39]
We would like to improve the test coverage of the projects in the [jupyterhub organization](https://github.com/jupyterhub). This microtask will help with achieving this goal and get you familiarized with the testing infrastructure across different JupyterHub projects, as well as how to write and run the tests.

**Multiple Outreachy applicants can work on this issue at the same time.**

1. Look at the [coverage reports](https://app.codecov.io/gh/jupyterhub) of various jupyterhub project repositories
2. Find an area of code that isn't covered by the tests. You can choose whatever repository in https://app.codecov.io/gh/jupyterhub, as long as there is coverage data available for it. 
3. Find the relevant section of the tests that cover similar things in its corresponding repository from GitHub https://github.com/jupyterhub
4. Add a test that covers the case by following the next steps:
    - [create a fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) of your chosen repository (the one you want to add the test to)
    - [create a new branch on your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository) to do your work on. You should add the test when on this branch.
5. In its corresponding GitHub repository, [open a Pull Request from your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) with these changes.
6. Register the URL of this Pull Request in the following [spreadsheet](https://docs.google.com/spreadsheets/d/1iGPccBrgpSpzMB5B2Te-3UKKj8HmNT9r22RmlU81m7U/edit?usp=sharing).

**Comment by SheilaKahwai** [comment]
@GeorgianaElena @sgibson91 @minrk I am interested in working on this issue. I am looking into it.

**Comment by Sheila-nk** [comment]
@GeorgianaElena @sgibson91 @minrk Hello, my name is Sheila and I am interested in working on this issue. I am looking into it.

**Comment by audrey2001** [comment]
Hi @sgibson91 , My name is Akaeze Kosiso and i would love to work on this

**Comment by Sheila-nk** [comment]
@minrk informed me that there is a problem on BinderHub CI where the tests aren't completing and coverage is wrong so he has recommended I choose a different repository. I am currently looking into the dockerspawner repo. Will update on any progress.

**Comment by Motunrayo321** [comment]
Hello @GeorgianaElena, I would like to work on this issue. I'll keep you updated about any progress I make.

**Comment by wangkaruru** [comment]
hey @sgibson91 I am interested in working on this task. Will keep you updated on my progress. Thanks

**Comment by Sheila-nk** [comment]
I have added allowed images and host ip tests to improve coverage for the dockerspawner repo. I have created a PR but the tests fail when the callable of allowed images returns a list, both locally and on github actions. I am working to find a solution but I would appreciate any assistance or recommendations. Thanks :)

#https://github.com/jupyterhub/dockerspawner/pull/467

**Comment by Sheila-nk** [comment]
> I have added allowed images and host ip tests to improve coverage for the dockerspawner repo. I have created a PR but the tests fail when the callable of allowed images returns a list, both locally and on github actions. I am working to find a solution but I would appreciate any assistance or recommendations. Thanks :) [view pull request here](https://github.com/jupyterhub/dockerspawner/pull/467)

Update: The bug has been fixed and the pull request has been merged! 😄

**Comment by GeorgianaElena** [comment]
### Update

Hey all! I have updated [the top comment](https://github.com/jupyterhub/outreachy/issues/39#issue-1397562448) with a final step, which is to add the link to the PR into a [spreadsheet](https://docs.google.com/spreadsheets/d/1iGPccBrgpSpzMB5B2Te-3UKKj8HmNT9r22RmlU81m7U/edit#gid=0), to track your awesome work more easily.

**Comment by GeorgianaElena** [comment]
> Update: The bug has been fixed and the pull request has been merged! 😄

Congratulations @Sheila-nk 🎉 and thanks for improving the test coverage of https://github.com/jupyterhub/dockerspawner. I have just added the link to your PR in the spreadsheet, as an example.

**Comment by Joel-Ando** [comment]
#41 https://github.com/jupyterhub/jupyterhub/pull/4141

**Comment by sgibson91** [comment]
Thank you everyone for your contributions!
