### ISSUE TITLE
Add user name to control panel in JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/outreachy#4]
See https://github.com/jupyterhub/jupyterhub/issues/2157

**Comment by sashafierce** [comment]
Hello @yuvipanda! I am an outreachy aspirant and would like to start with this task.

**Comment by sashafierce** [comment]
I have setup the development environment, accessed the local server, while logging in I used my Linux machine's auth credentials. I understand this so far, it is required to show the current user under control panel in locally run JupyterHub instance (I have thought of an appropriate placement, refer screen-shot), can you please clarify " this is not obvious with a bunch of Authenticators"
![jupyter](https://user-images.githubusercontent.com/18103181/45867502-3f0cfc00-bda1-11e8-93ad-d84cf5b84624.png)

**Comment by minrk** [comment]
@sashafierce welcome! That screenshot looks perfect. I don't believe the "this is not obvious" comment should be relevant. The username should be available as `user.name` in the jinja template. Feel free to ask further questions here or [on gitter](https://gitter.im/jupyterhub/jupyterhub)

**Comment by sashafierce** [comment]
@minrk  @yuvipanda Thanks for the guidance! I don't have much web development experience but I gained a good exposure with this issue, learned basics of jinja and tornado framework, hoping to learn further!

**Comment by minrk** [comment]
@sashafierce great job! This has been merged into jupyterhub master as https://github.com/jupyterhub/jupyterhub/pull/2164
