### ISSUE TITLE
Improve a page of JupyterHub documentation

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/outreachy#41]
Documentation can go stale very quickly in active projects and often there's always someway it can be improved. Maybe some setup steps have changed; the wording is a little confusing and could be clearer; maybe adding a screenshot or diagram will help? This task invites you to make an improvement to one of our documentation pages and will test your technical writing skills alongside git/GitHub workflows.

**Many applicants can work on this issue at the same time.**

1. Select a page of the documentation you'd like to improve from [this spreadsheet](https://docs.google.com/spreadsheets/d/1P_zlCToXJg5yAPq9nfyOmCb3PwmD4cbfcdnNyiJdsiY/edit?usp=sharing) by adding your GitHub handle to the "Work in progress" column. It's ok to pick a page if there is a name in the "Done" column, but try to avoid picking a page that already has someone's name in the "Work in progress" column. This will help us reduce merge conflicts later on.
2. Make your improvements to the page
	* [Fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) the [jupyterhub repo](https://github.com/jupyterhub/jupyterhub)
	* [Create a new branch on your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository) to track your work on. You should make changes to the docs on this branch.
3. [Open a Pull Request from your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) to the jupyterhub repo.
4. **Once your PR has been merged,** move your GitHub handle from the "Work in progress" column to the "Done" column in [the spreadsheet](https://docs.google.com/spreadsheets/d/1P_zlCToXJg5yAPq9nfyOmCb3PwmD4cbfcdnNyiJdsiY/edit?usp=sharing)

### Update

This microtask will be closed to new applicants on **Monday 24th October** (end of day UK time).

Please make sure your contributions are recorded and begin your final application on the Outreachy website. If your issue/PR is still open when we close this project, **it will still count as a contribution**. Closing the project **will not** affect your ability to record contributions and make your final applications.

**Comment by ydv-sahitya** [comment]
quick question: Do all the Docs pages link in the spreadsheet, those docs need an update, or what do we have to improve?

**Comment by mahamtariq58** [comment]
I would like to work on this issue!!

**Comment by sgibson91** [comment]
> quick question: Do all the Docs pages link in the spreadsheet, those docs need an update, or what do we have to improve?

Each link is a singular docs page. Just choose one of them to improve, whichever you think you can provide a contribution to. We worked it like this so multiple Outreachy applicants can work on this issue simultaneously.

**Comment by ydv-sahitya** [comment]
> We worked it like this so multiple Outreachy applicants can work on this issue simultaneously.

thank you

**Comment by NPDebs** [comment]
Hi Dr @sgibson91. I'd love to work on this issue, please! 🙂

**Comment by ToobaJamal** [comment]
Hi @sgibson91, which branch should I choose for comparing the changes? Thanks!

**Comment by Mackenzie-OO7** [comment]
I'm having trouble committing the changes suggested to my PR. When I hover on the "Add Suggestions to batch" button, it says "batching suggestions must be done from the files tab". Is there another way I can incorporate all the changes into a single commit instead of applying the changes individually?

**Comment by minrk** [comment]
@Mackenzie-OO7 yes, if you select the "Files changed tab" here:
![Screen Shot 2022-10-10 at 11 00 16](https://user-images.githubusercontent.com/151929/194831463-ccd445e0-0290-4dba-89fd-55cc9da6fa57.png)

you will be able to bundle all of the suggestions into one commit

**Comment by Mackenzie-OO7** [comment]
> @Mackenzie-OO7 yes, if you select the "Files changed tab" here: ![Screen Shot 2022-10-10 at 11 00 16](https://user-images.githubusercontent.com/151929/194831463-ccd445e0-0290-4dba-89fd-55cc9da6fa57.png)
> 
> you will be able to bundle all of the suggestions into one commit

It worked! Thank you.

**Comment by sgibson91** [comment]
> Hi @sgibson91, which branch should I choose for comparing the changes? Thanks!

`main`/`master` please (I forget the exact name of it! 😆 )

**Comment by Teniola-theDev** [comment]
Hello! I would love to work on this issue:
https://github.com/jupyterhub/jupyterhub/blob/main/docs/source/reference/spawners.md
I am assuming I would need to mention the link to the doc page I would love to work on, here in GitHub, in order to be assigned to it.

**Comment by melissakirabo** [comment]
Hi,
I am from Outreachy and I have made some changes to, and updated the index.rst file
https://github.com/jupyterhub/jupyterhub/pull/4084

**Comment by ToobaJamal** [comment]
@sgibson91 I have made a PR, please check it out :)
https://github.com/jupyterhub/jupyterhub/pull/4074

**Comment by sgibson91** [comment]
> I am assuming I would need to mention the link to the doc page I would love to work on, here in GitHub, in order to be assigned to it.

Hi @Teniola-theDev. We are using [this spreadsheet](https://docs.google.com/spreadsheets/d/1P_zlCToXJg5yAPq9nfyOmCb3PwmD4cbfcdnNyiJdsiY/edit?usp=sharing) to track who is working on which page.

**Comment by ArafatAbdussalam** [comment]
Hi @sgibson91 https://github.com/jupyterhub/jupyterhub/pull/4086

**Comment by Joel-Ando** [comment]
Hi!
 Please how do we add a link when editing a document. Need help please!!!

**Comment by Mackenzie-OO7** [comment]
> Hi! Please how do we add a link when editing a document. Need help please!!!

Hey, This [markdown guide](https://www.markdownguide.org/cheat-sheet/) should help you with that.

**Comment by alwasega** [comment]
Hello, 
If I change the main title of a document, will doing so break something else? And so, is it advisable to change the main title of a document to reflect changes made to the doc?

**Comment by NPDebs** [comment]
> Hello, 
> If I change the main title of a document, will doing so break something else? And so, is it advisable to change the main title of a document to reflect changes made to the doc? 

Hi @alwasega 👋🏼
Renaming files on a large project like this is never a good idea. You might break the existing, well-established network of information.

That said, what do you mean my making changes reflect?

**Comment by Joel-Ando** [comment]
> > Hi @sgibson91, which branch should I choose for comparing the changes? Thanks!
> 
> `main`/`master` please (I forget the exact name of it! 😆 )

Hi! Mrs @sgibson91 please i saw the below code block on one of the documentation.
1) this are json's why are they in single quotes?

**Comment by alexanderchosen** [comment]
Hello @sgibson91, I am Alexander, an Outreachy Intern from Nigeria.
Please can I get assigned to this project? I have read through the instructions given above and I have started working on the documentation.
Thanks

**Comment by alwasega** [comment]
> > Hello,
> > If I change the main title of a document, will doing so break something else? And so, is it advisable to change the main title of a document to reflect changes made to the doc?
> 
> Hi @alwasega 👋🏼 Renaming files on a large project like this is never a good idea. You might break the existing, well-established network of information.
> 
> That said, what do you mean my making changes reflect?

Thanks for your response @NPDebs. Yes, I had a feeling that making such a change could break something else somewhere, hence my query. What I meant by making changes reflect is that I was working on a document with the title `Starting servers with the JupyterHub API` but the entire document reads more of like `Managing servers with the JupyterHub API` as starting a server is only one of the many steps covered within it.

**Comment by NPDebs** [comment]
> > > Hello,
> > > If I change the main title of a document, will doing so break something else? And so, is it advisable to change the main title of a document to reflect changes made to the doc?
> > 
> > Hi @alwasega 👋🏼 Renaming files on a large project like this is never a good idea. You might break the existing, well-established network of information.
> > 
> > That said, what do you mean my making changes reflect?
> 
> Thanks for your response @NPDebs. Yes, I had a feeling that making such a change could break something else somewhere, hence my query. What I meant by making changes reflect is that I was working on a document with the title `Starting servers with the JupyterHub API` but the entire document reads more of like `Managing servers with the JupyterHub API` as starting a server is only one of the many steps covered within it. 
> Therefore, I felt `Managing` is better as part of the title than `Starting`, as it reflects the contents of the page better. 

Ah. I see...
That's a very brilliant observation, actually. 💡 

Here's what I'd suggest. In the description of your PR, suggest the new title and wait for feedback from the reviewer(s). 👍🏻

**Comment by NPDebs** [comment]
@alwasega Ah. I see...
That's a very brilliant observation, actually. 💡 

Here's what I'd recommend. In the description of your PR, suggest the new title and wait for feedback from the reviewer(s). 👍🏻

**Comment by alwasega** [comment]
> @alwasega Ah. I see... That's a very brilliant observation, actually. bulb
> 
> Here's what I'd recommend. In the description of your PR, suggest the new title and wait for feedback from the reviewer(s). 👍🏻

Let me do so. Thanks a lot for your help, @NPDebs!

**Comment by NPDebs** [comment]
> > @alwasega Ah. I see... That's a very brilliant observation, actually. bulb
> > 
> > Here's what I'd recommend. In the description of your PR, suggest the new title and wait for feedback from the reviewer(s). 👍🏻
> 
> Let me do so. Thanks a lot for your help, @NPDebs!

You're most welcome! 🙂🚀

**Comment by alexanderchosen** [comment]
@sgibson91 please how can I get Jupiter's official images? 
Thanks

**Comment by NPDebs** [comment]
> @sgibson91 I worked on a issue (https://github.com/jupyterhub/jupyterhub/issues/3875) that required fixing the documentation. This is the pull request https://github.com/jupyterhub/jupyterhub/pull/4092

Hi, @Temidayo32. 😃
You can tag Sarah directly in a comment, right under the PR. Or better still, request a review from the mentors. 

That should potentially get you a quicker response...and also keep the sections clean. 🙂 👍🏻

**Comment by EstherChristopher** [comment]
Hi, @sgibson91. I made a little adjustment to one page of the documentation and went ahead to create a pull request. Here it is [https://github.com/jupyterhub/jupyterhub/pull/4109](https://github.com/jupyterhub/jupyterhub/pull/4109). I hope it gets merged.

**Comment by EstherChristopher** [comment]
Hi @GeorgianaElena, I made some improvements to another documentation and made a pull request. You can check it out here [https://github.com/jupyterhub/jupyterhub/pull/4113](https://github.com/jupyterhub/jupyterhub/pull/4113). I look forward to seeing it merged, thanks.

**Comment by alexanderchosen** [comment]
Hello mentors @GeorgianaElena @sgibson91 @minrk, I properly reviewed the config-user-env.md under issue#41 with the aim of simplifying it for easy use for all kinds of users. Please check it out here https://github.com/jupyterhub/jupyterhub/pull/4114
I look forward to your feedback. Thanks

**Comment by falyne** [comment]
hello @sgibson91 i worked on the troubleshooting page kindle review https://github.com/jupyterhub/jupyterhub/pull/4117#issue-1408780087

**Comment by Beamps-code** [comment]
Here is  a [LINK](https://miro.com/app/board/uXjVPN8og-Q=/?share_link_id=236182799519) to my miro board
After using the Diataxis framework to analyze the documentation of the “**Get started section”,** my inference is as follows, there are no tutorials to help new users get familiar, but rather **“How-To Guides”** for users who already have basic competency. Also, there are not enough references for users to quickly consult for an in-depth technical description of the product.

2)Where will I create more documentation to help users or developers?

I will create more documentation in both tutorials and references, to help new users achieve basic competency and provide quick consultations about the product for everyone.

3)Could the present documentation be redistributed more evenly across the quadrants? How so?

No, it is adequately distributed among the 4 quadrants, it is the **Getting Started** section, and because of this, most of the documentation fell under the **“How-To Guides”**.

4) Did you find a particular page that could be improved or changed? What would you like to see happen that would improve it?

Yes, I will improve on the following pages; Configuration Basics, Frequently asked questions and Institutional FAQ, Security settings, and Authentication and User Basics

**Configuration settings:** The configuration basics document is useful if the user is already familiar with technical terms, but if that is not the case, it will be challenging for new users to complete the tasks, I will create a 3-minute tutorial to help new users get started. 

**Frequently asked questions and Institutional FAQ: I** will make institutional FAQ a subset of “Frequently asked questions” to limit confusion among users because, they might know the difference between the two, and they might be looking for answers in the place.

**Security settings and Authentication and User Basics**: The language used to depict warnings or notices should be consistent for all documentation, the use of different colors brings about disorganization in the document structure, I will use one color for warnings and notices in all the sub-sections

**Comment by Chimatara** [comment]
Hello!
I'll like to work on this project.

**Comment by Joel-Ando** [comment]
Hi, Mrs @GeorgianaElena, Mrs@sgibson91and  Mr@minrk  i open a pull request on the following  documentation
(check it out here)[https://github.com/Joel-Ando/jupyterhub/pulls] waiting for your reviews thanks.

**Comment by sgibson91** [comment]
@Joel-Ando Your Pull Requests are opened to be merged back into the default branch _of your fork_, not the original JupyterHub repo. Please read up on how to open PRs from forks here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by sgibson91** [comment]
### Update

This microtask will be closed to new applicants on **Monday 24th October** (end of day UK time).

Please make sure your contributions are recorded and begin your final application on the Outreachy website. If your issue/PR is still open when we close this project, **it will still count as a contribution**. Closing the project **will not** affect your ability to record contributions and make your final applications.

**Comment by ToobaJamal** [comment]
Hi @sgibson91, can I put any contribution URL in the final application form if there is more than one? Thanks!

**Comment by sgibson91** [comment]
> can I put any contribution URL in the final application form if there is more than one?

Please record each contribution separately with their own specific URL. That will help us find all your contributions when we review your applications.

**Comment by Joel-Ando** [comment]
> > can I put any contribution URL in the final application form if there is more than one?
> 
> Please record each contribution separately with their own specific URL. That will help us find all your contributions when we review your applications.

please Mrs @sgibson91 what is the right link for jupyterHub RBAC

**Comment by sgibson91** [comment]
This issue is now closed to new contributors. Thank you all for your contributions. Please remember to record them in Outreachy and submit your final application!

**Comment by sgibson91** [comment]
> please Mrs @sgibson91 what is the right link for jupyterHub RBAC frame work

It's the URL of your comment or PR for your contribution

**Comment by ToobaJamal** [comment]
@sgibson91 what are we supposed to write in the Outreachy internship project timeline? 
![Screenshot 2022-10-26 111127](https://user-images.githubusercontent.com/52610124/197948541-5b03a2f5-8aa7-4cc4-b3ce-e654d1399b77.png)

**Comment by sgibson91** [comment]
@ToobaJamal Please put together a rough timeline based on commitments you know you will have during the internship period. We will work with the successful applicant to fine-tune their timeline.
