### ISSUE TITLE
Make tljh-config error explicitly if called without `sudo`

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/outreachy#5]
See https://github.com/jupyterhub/the-littlest-jupyterhub/issues/120

**Comment by kyla-harper** [comment]
May I work on this task?

**Comment by yuvipanda** [comment]
@kyle-harper yes! Consider it assigned :)

**Comment by yuvipanda** [comment]
@kyla-harper gentle ping to see if you've made any progress :)

**Comment by kyla-harper** [comment]
@yuvipanda Not much, yet. Sorry about the delay, I've been caught up with my regular full time job and a few other life things. I do have time set aside to work on this today and the next few days though. :)

As a side note, I noticed that the installer script uses `apt-get` by default. I didn't see an issue opened for it yet but would it be okay for me to open a new issue to add options (or a set of checks) to use `pacman` and possibly `yum`? I never used `yum` before so I'm not sure if that would be appropriate to include it in the request just yet.

**Comment by yuvipanda** [comment]
@kyla-harper no worries! take your time :)

Currently, we only support installation on Ubuntu 18.04+ systems. I think adding additional system support would be complicated, so I'd prefer to not do that just now.

https://the-littlest-jupyterhub.readthedocs.io/en/latest/contributing/dev-setup.html should help you get a dev env set up even if you do not have apt-get on your local system.

**Comment by kyla-harper** [comment]
Ah, okay. Thanks for the clarification and the link!

**Comment by anyushevai** [comment]
@yuvipanda , @kyla-harper  hi! 
Is this issue still being worked on? If not I would like to participate here.

**Comment by kyla-harper** [comment]
Hi @anyushevai, I'm finding that I have a lot less time to work on this than anticipated. I would say you should check in with @yuvipanda since he's the maintainer. I would be happy to remove myself from this task for someone else to work on this.

**Comment by minrk** [comment]
@kyla-harper thanks for making room. Feel free to check back in on another task if you feel you have the time.

**Comment by minrk** [comment]
@anyushevai consider this task assigned to you

**Comment by minrk** [comment]
Great job, @anyushevai!

**Comment by anyushevai** [comment]
@minrk Thank you!

**Comment by choldgraf** [comment]
wooo! 🎉
