### ISSUE TITLE
Accessibility: Jupyter About Page

### ISSUE THREAD

**Issue by brendamoreira** [jupyterhub/outreachy#55]
### What page is this for?

https://github.com/jupyterhub/outreachy/issues/38#issuecomment-1273541852

## Jupiter "About" page Wave evaluation:

<img width="1440" alt="Screenshot 2022-10-14 at 13 32 28" src="https://user-images.githubusercontent.com/62898120/195837414-1d7570b7-e61a-4cc4-a54b-2e038d896c6c.png">

### Detailed contrast errors and alerts & contrast information:

<img width="266" alt="Screenshot 2022-10-14 at 13 36 14" src="https://user-images.githubusercontent.com/62898120/195837674-49732ed1-e97a-45a8-bf3a-60029ad3384c.png">

<img width="349" alt="Screenshot 2022-10-14 at 13 51 24" src="https://user-images.githubusercontent.com/62898120/195840402-7c785bfe-5c04-4fbf-be4f-35dd576b0133.png"><img width="350" alt="Screenshot 2022-10-14 at 13 53 13" src="https://user-images.githubusercontent.com/62898120/195840659-bae21020-ef39-40b8-bc75-792e4178288f.png">
(The first image represent the first and second contrast information. The second image represents the third one)

### Structural elements (showing on the page the ones that do not belong):
<img width="1438" alt="Screenshot 2022-10-14 at 13 37 13" src="https://user-images.githubusercontent.com/62898120/195837812-78285d3f-a8a9-48cf-9d51-4cb445eac624.png">

### ARIA label (examples):
<img width="1435" alt="Screenshot 2022-10-14 at 13 42 26" src="https://user-images.githubusercontent.com/62898120/195838799-822f602b-e385-4b7f-b600-6316f04fdb8b.png">

### The HTML element to be changed

```html
Contrast Errors:
<a href="https://opensource.org/licenses/BSD-3-Clause" style="color: rgb(197, 84, 11); background-color: rgb(245, 245, 245);">(...)</a>
<a href="https://numfocus.org" style="color: rgb(197, 84, 11); background-color: rgb(245, 245, 245);">(...)</a>
<div class="orange-button"><a href="https://numfocus.salsalabs.org/donate-to-jupyter/index.html" target="noopener noreferrer" style="color: rgb(255, 255, 255); background-color: rgb(228, 110, 46);">(...)</a></div>    
.about-box .orange-button {
    background-color: #e46e2e;
(...)
}

Alerts (redundant alternative text):
<img class="biocard-photo" alt="Mehmet Bektas" src="/assets/bios/Mehmet_Bektas.jpg" (...)>
<img class="biocard-photo" alt="David Brochart" src="/assets/bios/David_Brochart.jpg" (...)>

Alert(long alternative text):
<img src="/assets/logos/EC-H2020.svg" alt="Horizon 2020 European Union funding for Research and Innovation logo - OpenDreamkit funded project - Home Page" (...)>

Structural elements:
<h2 id="project-jupyter">Project Jupyter<a (...)></a></h2><ul><li>(...)</li></ul>
<h2 id="subprojects">Subprojects<a (...)></a></h2><ul><li>(...)</li></ul>
<h2 id="follow-us">Follow us<a (...)></a></h2><ul><li>(...)</li></ul>

ARIA labels:
<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon=" " href="#distinguished-contributors" (...)></a>
<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="#2021-cohort" (...)></a>
<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="#2020-cohort" (...)></a>
<a class="anchorjs-link " aria-label="Anchor" data-anchorjs-icon="" href="#special-election-cohort" (...)></a>
```

### Your proposed HTML (or CSS), after change

```html
Contrast Errors:
<a href="https://opensource.org/licenses/BSD-3-Clause" style="color: rgb(138, 55, 0);background-color: rgb(245, 245, 245);text-decoration: underline;">(...)</a>
<a href="https://numfocus.org" style="color: rgb(138, 55, 0); background-color: rgb(245, 245, 245);text-decoration: underline;">(...)</a>

<div class="orange-button"><a href="https://numfocus.salsalabs.org/donate-to-jupyter/index.html" target="noopener noreferrer" style="color: rgb(0, 0, 0); background-color: rgb(228, 110, 46);">(...)</a></div>    
.about-box .orange-button {
    background-color: #E58957;
(...)
}

Alerts (redundant alternative text):
<img class="biocard-photo" alt="Mehmet Bektas avatar" src="/assets/bios/Mehmet_Bektas.jpg" (...)>
<img class="biocard-photo" alt="David Brochart avatar" src="/assets/bios/David_Brochart.jpg" (...)>

Alert(long alternative text):
<img src="/assets/logos/EC-H2020.svg" alt="Horizon 2020 European Union logo" (...)>

Structural elements:
<ul id="project-jupyter" style="font-size: 1.1em; font-weight: bold;">Project Jupyter<a (...)></a><li>(...)</li></ul>
<ul id="subprojects" style="font-size: 1.1em; font-weight: bold;">Subprojects<a (...)></a><li>(...)</li></ul>
<ul id="follow-us" style="font-size: 1.1em; font-weight: bold;">Follow us<a (...)></a><li>(...)</li></ul>

ARIA labels:
<a class="anchorjs-link " aria-label="Distinguished Contributors section link" data-anchorjs-icon=" " href="#distinguished-contributors" (...)></a>
<a class="anchorjs-link " aria-label="2021 Cohort section link" data-anchorjs-icon="" href="#2021-cohort" (...)></a>
<a class="anchorjs-link " aria-label="2020 Cohort section link" data-anchorjs-icon="" href="#2020-cohort" (...)></a>
<a class="anchorjs-link " aria-label="Special Election Cohort section link" data-anchorjs-icon="" href="#special-election-cohort" (...)></a>
```

### More info

By creating this issue I realised that the 70th alert, the redundant link, is not present in the original website, but the wave itself makes the link become redundant and point it as wrong, so it doesn't really exist. So no changes suggested for it.
For all of the 68 alerts about redundant alternative text my suggestion is to add the word "avatar" in the end of the alt. I only put two examples in the code suggestion to not be redundant myself, and to present a more succinct code, since there are a lot of other changes to be presented.
I did the same about the ARIA labels, only put four examples so it wouldn't be so long. But the suggestion is to change the `anchor` by putting the name of the section adding `section link` at the end, as shown in the proposed html change.

_p.s.: I didn't know if was best not to add text to separate the HTML per error, but I believe that would be better to be understood. If necessary I can change._

**Comment by minrk** [comment]
Great suggestions and explanations, thank you!
