### ISSUE TITLE
Write a traefik toml configuration for prefix-based routing

### ISSUE THREAD

**Issue by minrk** [jupyterhub/outreachy#7]
[traefik](https://traefik.io) is a proxy application that we want to use in JupyterHub. We want to be able to configure it to replace [configurable-http-proxy](https://github.com/jupyterhub/configurable-http-proxy). But first, we need to understand its configuration.

The first step to understanding traefik is to write a [toml configuration file](https://docs.traefik.io/configuration/entrypoints/) to configure traefik.
For JupyterHub, we need the ability to route by URL prefix so that requests to `/user/yourname` are routed to one server, while requests to `/otherthings` are routed to a different 

1. get [traefik](https://traefik.io)
2. write a traefik.toml [config file](https://docs.traefik.io/configuration/entrypoints/) that routes to different backends based on the URL. The following URLs should be routed to different servers:
  - `/` (default backend, unless a more specific match is found)
  - `/user/first` route to one backend
  - `/user/second` route to another backend
3. write some tests (e.g. with pytest) to verify the behavior.

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here if you have questions :)

**Comment by GeorgianaElena** [comment]
I've worked with Apache Traffic Server in the past and I'd love to investigate how traefik works as well. I will give this issue a try.

**Comment by minrk** [comment]
@GeorgianaElena great! It may be useful to look at the littlest jupyterhub's [traefik config template](https://github.com/jupyterhub/the-littlest-jupyterhub/blob/master/tljh/traefik.toml.tpl) as a reference, which sets up http[s], but not the path-based routing part.

**Comment by GeorgianaElena** [comment]
Thanks a lot! Do you think it would be better to work directly in that littlest jupyterhub repo? We might be able to reuse some of the code there instead of duplicating it here.

**Comment by minrk** [comment]
I wouldn't for this one. I would mainly look at that traefik.toml file as an example, and write a standalone traefik.toml to test. The [PathPrefix matcher](https://docs.traefik.io/basics/#matchers) is probably a key configuration to understand.

**Comment by GeorgianaElena** [comment]
Hi @minrk, I've just added a pull request with my progress so far. At the moment I have a toml file and a dummy py server that helps me test the functionality. I have a local traefik instance running with this config file and I've tested it using the python server and some curl calls, everything seems to be working as required.

Before writing the tests, I want to make sure I'm on the right path. Currently I have deployed a local traefik instance and 3 instances of the python server running on 3 different ports (as 3 traefik backends). The server only knows to reply with the port number to a GET request. I launched a bunch of curl calls to traefik requesting different paths and I made sure the correct backend is hit (the replied port number is the one set in the toml file).

In terms of testing, should I assume that there is a traefik instance already running on a specific port or should I follow the littlest jupyterhub model and download the binary and everything?

**Comment by minrk** [comment]
Hi @GeorgianaElena! Could you open it as a PR to this repo instead of jupyterhub/jupyterhub? This is an experiment for developing information that will ultimately go in a repo we haven't created yet, so I think here is the right place for now.

**Comment by GeorgianaElena** [comment]
Thanks a lot @minrk and sorry for the PR to the wrong repo.

**Comment by minrk** [comment]
folks can see the result of this task in #17 and #19. Thank you, @GeorgianaElena!
