### ISSUE TITLE
Pytest Plugin: Pytest-auth

### ISSUE THREAD

**Issue by Uzor13** [jupyterhub/outreachy#76]
### Please share the URL of pytest plugin you have created?

https://github.com/Uzor13/pytest-auth

### Please share the URL to your fork of `FirstUseAuthenticator` where you have integrated the plugin

https://github.com/Uzor13/firstuseauthenticator

### Whether or not you managed to run the `FirstUseAuthenticator` tests succesfully

Yes, the tests run

**Comment by sgibson91** [comment]
Thank you for your contribution! Since the contribution period is now over, we will close this issue.
