### ISSUE TITLE
Accessibility: Jupyter's Community Page

### ISSUE THREAD

**Issue by Uzor13** [jupyterhub/outreachy#79]
### What page is this for?

https://jupyter.org/community

### WAVE accessibility report

<img width="360" alt="Screenshot 2022-10-10 at 11 42 31 AM" src="https://user-images.githubusercontent.com/40992425/196351988-cc8206fd-3d7c-48c5-9d92-865cef9c85ad.png">

- Contrast errors: The view buttons have contrast issues because the text has a lesser ratio than the background colour due to its size. Increasing the text size or decreasing the brightness of the button can help with the contrast issue.
- Suspicious link text: Using ambiguous words that do not describe the link would not help users have an understanding of what they're clicking on. Using more descriptive text like See community content rather than using this page would give users and screen readers more context.
- Redundant links: Adjacent links that go to the same URL. Combining the link text into one and giving more information would help users not bounce around the same page.

### The HTML element to be changed

```html
<div class="col-md-2 resource-button">
<a href="https://github.com/jupyter/" style="color: rgb(255, 255, 255); background-color: rgb(228, 110, 46);">
View
</a>
</div>
The colour contrast between the button and text is at 3.19:1 rather than 4:5:1

<a href="https://jupyter.readthedocs.io/en/latest/community/content-community.html#jupyter-wide-meetings">
this page
</a>
It has a generic link name which can be suspicious for some users
```

### Your proposed HTML (or CSS), after change

```html
<a href="https://github.com/jupyter/">
<button class="col-md-2 resource-button" style="color: rgb(255, 255, 255); background-color: rgb(204, 71, 0);">
View
</button>
</a>
Reducing the brightness of the background text increases the contrast to 4.69:1, also making the button semantic by using a button element rather than a div for all the 9 buttons on the page

<a href="https://jupyter.readthedocs.io/en/latest/community/content-community.html#jupyter-wide-meetings">
the calendar
</a>
```

**Comment by sgibson91** [comment]
Thank you for your contribution! Since the contribution period is now over, we will close this issue.
