### ISSUE TITLE
Improve test coverage of JupyterHub

### ISSUE THREAD

**Issue by minrk** [jupyterhub/outreachy#8]
Testing is important to maintaining software, and we can always have more tests! One good way to learn about a code base can be to look at coverage reports and see what isn't covered, and look for a way to add a test to cover that case. Doing so helps you learn:

1. about the structure of the project
2. how testing for the project works
3. how to write and run tests

Steps:

1. look at the jupyterhub [coverage report](https://codecov.io/gh/jupyterhub/jupyterhub/tree/master/jupyterhub)
2. find an area of code that isn't covered by the tests (often an `if some_condition` that isn't covered)
3. find the relevant section of the tests that cover similar things
4. add a test that covers the case
5. open a pull request to https://github.com/jupyterhub/jupyterhub with your new test

Remember, you don't need to already know how to do all this! We'll help you. Respond to the issue here or [on gitter](https://gitter.im/jupyterhub/jupyterhub) if you have questions :)

**Comment by nfatma** [comment]
Hello! I am Nahid, an outreachy applicant and I want to give this issue a try

**Comment by minrk** [comment]
Welcome! Feel free to ask questions here or on Gitter for guidance.

**Comment by Naba7** [comment]
hello, can I work on this? I am an outreachy applicant

**Comment by minrk** [comment]
@Naba7 yes, any number of applicants can do this task at the same time.

**Comment by narnt** [comment]
Hello! I am Maria, an outreachy applicant, can I also work on this task?

**Comment by minrk** [comment]
@narnt yes! Any number of applicants can do this.

**Comment by narnt** [comment]
It was too hard for me(

**Comment by sgibson91** [comment]
Thank you for your contributions! I am closing this issue now as it pertains to a previous round of Outreachy.
