### ISSUE TITLE
My pytest plugin

### ISSUE THREAD

**Issue by luquiceno** [jupyterhub/outreachy#80]
### Please share the URL of pytest plugin you have created?

https://github.com/luquiceno/pytest-pluginlu

### Please share the URL to your fork of `FirstUseAuthenticator` where you have integrated the plugin

https://github.com/luquiceno/firstuseauthenticator

### Whether or not you managed to run the `FirstUseAuthenticator` tests succesfully

Yes, the tests run

**Comment by sgibson91** [comment]
Thank you for your contribution! Since the contribution period is now over, we will close this issue.
